// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQZCjarAxKVNZosjiBO9yfxoICluDd6A',
    appId: '1:659453986642:web:c16739c3203cf9e4305c8b',
    messagingSenderId: '659453986642',
    projectId: 'mygpaa-a67b7',
    authDomain: 'mygpaa-a67b7.firebaseapp.com',
    storageBucket: 'mygpaa-a67b7.firebasestorage.app',
    measurementId: 'G-1GG89GFDR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg16krfnd2meOHwOLWgikGjEjBmXyi12E',
    appId: '1:659453986642:android:86df4c76811b0467305c8b',
    messagingSenderId: '659453986642',
    projectId: 'mygpaa-a67b7',
    storageBucket: 'mygpaa-a67b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoe-Vo1elB10lGeFzg16v3qmzUrLztRgo',
    appId: '1:659453986642:ios:45f0fd8430786f46305c8b',
    messagingSenderId: '659453986642',
    projectId: 'mygpaa-a67b7',
    storageBucket: 'mygpaa-a67b7.firebasestorage.app',
    iosBundleId: 'com.example.newspaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoe-Vo1elB10lGeFzg16v3qmzUrLztRgo',
    appId: '1:659453986642:ios:45f0fd8430786f46305c8b',
    messagingSenderId: '659453986642',
    projectId: 'mygpaa-a67b7',
    storageBucket: 'mygpaa-a67b7.firebasestorage.app',
    iosBundleId: 'com.example.newspaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFQZCjarAxKVNZosjiBO9yfxoICluDd6A',
    appId: '1:659453986642:web:4ea0d85cdf0fd42c305c8b',
    messagingSenderId: '659453986642',
    projectId: 'mygpaa-a67b7',
    authDomain: 'mygpaa-a67b7.firebaseapp.com',
    storageBucket: 'mygpaa-a67b7.firebasestorage.app',
    measurementId: 'G-KXL7J8G3TS',
  );
}
